version: "3"
services:
  proxy:
    build: .
    ports:
      - "8081:8081"
    environment:
      - MAPPA_PROXY_PORT=8081

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    volumes:
      - "./web_out:/web_out:rw"
