# fly.toml file generated for mappa-proxy on 2022-11-11T11:36:03-03:00

app = "mappa-proxy"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[deploy]
strategy = "rolling"

[env]
MAPPA_PROXY_REPOSITORY = "sqlite:/data/mappa-proxy-repository-new.db"
CACHE_PATH = "/data/cache"

[experimental]
allowed_public_ports = []
auto_rollback = true

[mounts]
destination = "/data"
source = "mappa_proxy_data"

[[services]]
http_checks = []
internal_port = 5000
processes = ["app"]
protocol = "tcp"
script_checks = []
[services.concurrency]
hard_limit = 25
soft_limit = 20
type = "connections"

[[services.ports]]
force_https = true
handlers = ["http"]
port = 80

[[services.ports]]
handlers = ["tls", "http"]
port = 443

[[services.tcp_checks]]
grace_period = "1s"
interval = "15s"
restart_limit = 0
timeout = "2s"
