# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  swagger:
    cmds:
      - swag fmt
      - swag init

  deploy:
    cmds:
      - flyctl deploy

  test:
    cmds:
      - go test -coverprofile=coverage.out -parallel 4 ./...
      - go tool cover -html=coverage.out

  build:
    vars:
      BUILD_TIME:
        sh: date +%Y-%m-%dT%H:%M:%S%z
    env:
      CGO_ENABLED: 1
      GOOS: linux
    cmds:
      # - go build -ldflags="-X 'package_path.variable_name=new_value'"
      - go build -ldflags="-X 'main.Build={{.BUILD_TIME}}'" -o mappa_proxy .

  build_run:
    deps: [build]
    env:
      MAPPA_PROXY_REPOSITORY: sqlite:./mappa-proxy-repository.db
    cmds:
      - echo $MAPPA_PROXY_REPOSITORY
      - ./mappa_proxy
