basePath: /
definitions:
  handlers.BotRequestData:
    properties:
      cId:
        description: Chat ID
        type: integer
      mId:
        description: Message ID to respond to
        type: integer
      msg:
        description: Message
        type: string
    type: object
  handlers.ReplyMessage:
    properties:
      error:
        type: string
      message:
        type: string
    type: object
  infra.MemoryStatus:
    properties:
      alloc:
        description: Alloc is bytes of allocated heap objects.
        type: integer
      heap_alloc:
        description: HeapAlloc is bytes of allocated heap objects.
        type: integer
      num_gc:
        description: NumGC is the number of completed GC cycles.
        type: integer
      sys:
        description: Sys is the total bytes of memory obtained from the OS.
        type: integer
      total_alloc:
        description: TotalAlloc is cumulative bytes allocated for heap objects.
        type: integer
    type: object
  requests.LoginRequest:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  responses.FullConquistaResponse:
    properties:
      associado:
        $ref: '#/definitions/responses.MappaAssociadoResponse'
      codigoAssociado:
        type: integer
      codigoEscotistaUltimaAlteracao:
        type: integer
      codigoEspecialidade:
        type: integer
      dataConquista:
        type: string
      especialidade:
        $ref: '#/definitions/responses.MappaEspecialidadeResponse'
      numeroNivel:
        type: integer
      type:
        type: string
    type: object
  responses.HealthCheckResponse:
    properties:
      mappa_server:
        $ref: '#/definitions/responses.MappaServerResponse'
      status:
        type: string
    type: object
  responses.IndexResponse:
    properties:
      app:
        type: string
      build_time:
        type: string
      running_by:
        type: string
      version:
        type: string
    type: object
  responses.MappaAssociadoResponse:
    properties:
      codigo:
        type: integer
      codigoCategoria:
        type: integer
      codigoEquipe:
        type: integer
      codigoFoto:
        type: integer
      codigoRamo:
        type: integer
      codigoRamoAdulto:
        type: integer
      codigoSegundaCategoria:
        type: integer
      codigoTerceiraCategoria:
        type: integer
      dataAcompanhamento:
        type: string
      dataNascimento:
        type: string
      dataValidade:
        type: string
      linhaFormacao:
        type: string
      nome:
        type: string
      nomeAbreviado:
        type: string
      numeroDigito:
        type: integer
      sexo:
        type: string
      username:
        type: integer
    type: object
  responses.MappaDetalhesResponse:
    properties:
      associado:
        $ref: '#/definitions/responses.MappaAssociadoResponse'
      escotista:
        $ref: '#/definitions/responses.MappaEscotistaResponse'
      grupo:
        $ref: '#/definitions/responses.MappaGrupoResponse'
    type: object
  responses.MappaEscotistaResponse:
    properties:
      ativo:
        $ref: '#/definitions/types.Bool'
      codigo:
        type: integer
      codigoAssociado:
        type: integer
      codigoFoto:
        type: integer
      codigoGrupo:
        type: integer
      codigoRegiao:
        type: string
      nomeCompleto:
        type: string
      username:
        type: string
    type: object
  responses.MappaEspecialidadeItemResponse:
    properties:
      codigoEspecialidade:
        description: Id                  int    `json:"id"`
        type: integer
      descricao:
        type: string
      numero:
        type: integer
    type: object
  responses.MappaEspecialidadeResponse:
    properties:
      codigo:
        type: integer
      descricao:
        type: string
      itens:
        items:
          $ref: '#/definitions/responses.MappaEspecialidadeItemResponse'
        type: array
      prerequisito:
        type: string
      ramoConhecimento:
        type: string
    type: object
  responses.MappaGrupoResponse:
    properties:
      codigo:
        type: integer
      codigoModalidade:
        type: integer
      codigoRegiao:
        type: string
      nome:
        type: string
    type: object
  responses.MappaLoginResponse:
    properties:
      created:
        type: string
      id:
        type: string
      ttl:
        type: integer
      userId:
        type: integer
    type: object
  responses.MappaMarcacaoResponse:
    properties:
      codigoAssociado:
        type: integer
      codigoAtividade:
        type: integer
      codigoUltimoEscotista:
        type: integer
      dataAtividade:
        type: string
      dataHoraAtualizacao:
        type: string
      dataStatusEscotista:
        type: string
      segmento:
        type: string
    type: object
  responses.MappaProgressaoResponse:
    properties:
      codigo:
        type: integer
      codigoCaminho:
        type: integer
      codigoCompetencia:
        type: integer
      codigoDesenvolvimento:
        type: integer
      codigoRegiao:
        type: string
      codigoUeb:
        type: string
      descricao:
        type: string
      numeroGrupo:
        type: integer
      ordenacao:
        type: integer
      segmento:
        type: string
    type: object
  responses.MappaSecaoResponse:
    properties:
      codigo:
        type: integer
      codigoGrupo:
        type: integer
      codigoRegiao:
        type: string
      codigoTipoSecao:
        type: integer
      nome:
        type: string
      subsecoes:
        items:
          $ref: '#/definitions/responses.MappaSubSecaoResponse'
        type: array
    type: object
  responses.MappaServerResponse:
    properties:
      mappa_server_url:
        type: string
      memory:
        $ref: '#/definitions/infra.MemoryStatus'
      status:
        type: string
      status_code:
        type: integer
    type: object
  responses.MappaSubSecaoResponse:
    properties:
      associados:
        items:
          $ref: '#/definitions/responses.MappaAssociadoResponse'
        type: array
      codigo:
        type: integer
      codigoLider:
        type: integer
      codigoSecao:
        type: integer
      codigoViceLider:
        type: integer
      nome:
        type: string
    type: object
  types.Bool:
    type: object
info:
  contact:
    email: guionardo@gmail.com
    name: Guionardo Furlan
  description: This is a sample swagger for Fiber
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: mappa-api
  version: 0.5.2
paths:
  /:
    get:
      consumes:
      - application/json
      description: 'route: /'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.IndexResponse'
      summary: Index handler
      tags:
      - mappa-proxy
  /hc:
    get:
      description: Service healthcheck
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.HealthCheckResponse'
      summary: Healthcheck handler
      tags:
      - mappa-proxy
  /mappa:
    get:
      consumes:
      - application/json
      description: Adicione o caminho da requisição após /mappa/
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: object
      summary: Requisição genérica para a API do Mappa
      tags:
      - mappa-proxy
  /mappa/conquistas/{cod_secao}:
    get:
      consumes:
      - application/json
      parameters:
      - description: Código Seção
        in: path
        name: cod_secao
        required: true
        type: integer
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/responses.FullConquistaResponse'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.ReplyMessage'
      summary: Lista de conquistas da secão
      tags:
      - mappa-proxy
  /mappa/escotista/{userId}:
    get:
      consumes:
      - application/json
      description: Informações do escotista, associado e grupo
      parameters:
      - description: User ID
        in: path
        name: userId
        required: true
        type: integer
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.MappaDetalhesResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.ReplyMessage'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/handlers.ReplyMessage'
      summary: Detalhes do escotista
      tags:
      - mappa-proxy
  /mappa/escotista/{userId}/secoes:
    get:
      consumes:
      - application/json
      parameters:
      - description: User ID
        in: path
        name: userId
        required: true
        type: integer
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.MappaSecaoResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.ReplyMessage'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/handlers.ReplyMessage'
      summary: Seções do escotista
      tags:
      - mappa-proxy
  /mappa/especialidades:
    get:
      consumes:
      - application/json
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.MappaEspecialidadeResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.ReplyMessage'
      summary: Lista de especialidades e items
      tags:
      - db
  /mappa/login:
    post:
      consumes:
      - application/json
      description: User login
      parameters:
      - description: Login request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/requests.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.MappaLoginResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.ReplyMessage'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/handlers.ReplyMessage'
      summary: Mappa Login handler
      tags:
      - mappa-proxy
  /mappa/marcacoes/{cod_secao}:
    get:
      consumes:
      - application/json
      description: Lista de marcações da sessão
      parameters:
      - description: Código Seção
        in: path
        name: cod_secao
        required: true
        type: integer
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.MappaMarcacaoResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.ReplyMessage'
      summary: MappaMarcacoes handler
      tags:
      - mappa-proxy
  /mappa/progressoes/{ramo}:
    get:
      consumes:
      - application/json
      parameters:
      - description: Ramo
        enum:
        - L
        - E
        - S
        - P
        in: path
        name: ramo
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/responses.MappaProgressaoResponse'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.ReplyMessage'
      summary: Lista de progressões do ramo
      tags:
      - db
  /tg/pub:
    post:
      consumes:
      - application/json
      description: Publica mensagem em chat do Telegram
      parameters:
      - description: Bot request data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handlers.BotRequestData'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.ReplyMessage'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.ReplyMessage'
      summary: Telegram Publisher handler
      tags:
      - telegram
swagger: "2.0"
